- Python
    - python is a programing pardism means it supports programming and object oriented programming and also work will with porecdure  oriented program
- Procedure oriented language
    - procedure oriented means write our programming language using functions class
- obeject oriented language
    - A real word entity: or it aphysical entity represented the
    - class logical entity contains and logica of the application

In [ ]:
# Syntax
variable
method or functions

In [1]:
print('hai hello')

hai hello


In [2]:
8+9

17

In [3]:
class Hi:
    a=10
    b=30
    name="apssdc"
    def show():
        print("i am from show() finction")

In [4]:
Hi.name

'apssdc'

In [5]:
Hi.a

10

In [6]:
Hi.b

30

In [7]:
Hi.show()

i am from show() finction


In [9]:
print(Hi.a,Hi.b)

10 30


In [18]:
class Hi:
    name="apssdc"
    program_name="python"
    def display():
        print(" i am display function()")
    def show():
        print("i am from show function()")
print(Hi.name,Hi.program_name)
print(Hi.display())

apssdc python
 i am display function()
None


In [17]:
print(Hi.display())

 i am display function()
None


In [21]:
class Hello:
    def display():
        print(" i am display function()")
        return("i am from return function()")
    def show():
        print("i am from show function()")
print(Hello.display())
print(Hello.show())

 i am display function()
i am from return function()
i am from show function()
None


In [22]:
# in java obect declaration 
 # class_name obt_name-new_classname
# in python
    # obj_name=class_name

In [24]:
class Hi:
    name="apssdc"
    program_name="python"
    def display(self):
        print(" i am display function()")
        return("i am from return function()")
    def show():
        print("i am from show function()")
obj=Hi()
print(obj.name,obj.program_name)
print(obj.display())

apssdc python
 i am display function()
i am from return function()


### Constructor
- constructor without using object we will call methods
   - in java:: class name should be same as method name
   - in python:: we will use one special methods to definecomstructor
   -  __init(self)__

In [30]:
class Hai:
    def __init__(self,name,roll_no):
        self.name=name
        self.roll_no=roll_no
        print("Hai",self.name)
    def display(self):
        print("your roll_no is:",self.roll_no)
obj=Hai('snehaja','21A85A0502')
obj.display()

Hai snehaja
your roll_no is: 21A85A0502


### Inheritance
- Inheritance something from parent class to child class

class A:
    #a,b=10,20
class B(A):
    #c,d=30,40

In [35]:
class A:
    a,b=10,20
    def msg():
        print("i am from class A")
class B(A):
    c,d=30,40
    def msg1():
        print("i am from class B")
obj=B
print(obj.c,obj.d)
obj.msg1()
obj.msg()  

30 40
i am from class B
i am from class A


## Python Libraries for Data Science
- Organizinh,processing,analyzing the hug amount of data
- Apply data visulization 
- Extracting the data from source
- Narly 20 python libraries are there
    
#### Top
- Numpy
- Pandas
- Matplotlib

#### Numpy
- numpy:: (num+py)means numrical data+python
- It is fundemental package for scientific compuying in python
- numpy in python libraries
- It is used to create multidimensional for fast operation 
    - It dealing with mathmatical,scientific,statical data
- numpy contains a powerful n-dimensional array obects which in the foll
- we can intilize numpy array from nested python list

In [ ]:
# how to install numpy
- pip install numpy

In [40]:
# hpw to import and use numpy package 
import numpy as np

In [41]:
# how to find numpy version
np.__version__

'1.20.3'

In [43]:
# how to create numpy array
import numpy as np
a=np.array([1,2,3,4])# single dimensional number
print(a)
print(type(a))

[1 2 3 4]
<class 'numpy.ndarray'>


In [62]:
a2=np.array([[2,3,4],[5,6,8]])
print(a2)
print(type(a2))

[[2 3 4]
 [5 6 8]]
<class 'numpy.ndarray'>


In [47]:
# To know about the shape of the array
a2.shape


(2,)

In [48]:
li=[2,3,4,'h','i']
print(type(li))
a1=np.array(li)
print(a1)
print(type(a1))

<class 'list'>
['2' '3' '4' 'h' 'i']
<class 'numpy.ndarray'>


In [54]:
ar=np.array([[1,2],[3,4],[5,6]])
print(ar)

[[1 2]
 [3 4]
 [5 6]]


In [51]:
print(ar.dtype)

object


In [55]:
b=np.array([[1,2,3,4]])
print(b)

[[1 2 3 4]]


In [56]:
print(b.shape)

(1, 4)


In [57]:
b.itemsize

4

In [58]:
b.ndim

2

In [59]:
#range
a=np.array(range(10))
print(a)
print(type(a))
print(a.shape)
print(a.size)
b=np.array(range(1,10,2))
print(b)
print(b.ndim)

[0 1 2 3 4 5 6 7 8 9]
<class 'numpy.ndarray'>
(10,)
10
[1 3 5 7 9]
1


In [66]:
# Arange()- third party of numpy librariy
a=np.arange(10)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [67]:
a=np.arange(1,20,3)
a

array([ 1,  4,  7, 10, 13, 16, 19])

In [68]:
x=np.arange(10)
print(x.reshape(5,2))

[[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]


In [69]:
# Reshape of array
a1=np.array([1,2,3,4,5,6,7,8])
print(a1.shape)
print("before reshape",a1)
print(a1.ndim)
a2=a1.reshape(4,2)
print("after reshape",a2)
print(a2.shape)
print(a2.ndim)

(8,)
before reshape [1 2 3 4 5 6 7 8]
1
after reshape [[1 2]
 [3 4]
 [5 6]
 [7 8]]
(4, 2)
2


In [70]:
# Resize of array(its modifies shape and array itself)
a1=np.array([1,2,3,4,5,6,7,8])
print(a1)
print(a1.shape)
a1.resize(3)# resize the number of  elements for the original 
print(a1)
print(a1.shape)
a1.resize(3,3)
print(a1)
print(a1.shape)

[1 2 3 4 5 6 7 8]
(8,)
[1 2 3]
(3,)
[[1 2 3]
 [0 0 0]
 [0 0 0]]
(3, 3)


In [71]:
# Zero array 
import numpy as np 
a1=np.zeros(3)
a2=np.zeros((2,4))
print(a1.dtype)
print(a2.dtype)
print(a1)
print(a2)

float64
float64
[0. 0. 0.]
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [74]:
# One array 
a2=np.ones(3,dtype="int64")
print(a2)
np.ones((6,5),dtype="int64")

[1 1 1]


array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]], dtype=int64)

In [75]:
# Full  array -full(dimensions,specified number)
a=np.full((3,3),7)
a

array([[7, 7, 7],
       [7, 7, 7],
       [7, 7, 7]])

In [76]:
np.diag(a)

array([7, 7, 7])

In [78]:
np.full(3,100)

array([100, 100, 100])

In [79]:
np.full((3,9),500)

array([[500, 500, 500, 500, 500, 500, 500, 500, 500],
       [500, 500, 500, 500, 500, 500, 500, 500, 500],
       [500, 500, 500, 500, 500, 500, 500, 500, 500]])

In [81]:
# eye array
np.eye(6,dtype="int64")


array([[1, 0, 0, 0, 0, 0],
       [0, 1, 0, 0, 0, 0],
       [0, 0, 1, 0, 0, 0],
       [0, 0, 0, 1, 0, 0],
       [0, 0, 0, 0, 1, 0],
       [0, 0, 0, 0, 0, 1]], dtype=int64)

In [85]:
n=np.eye(5)
n

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [86]:
np.diag(n)

array([1., 1., 1., 1., 1.])

In [92]:
r=np.random.randint(1,10)
r

7

In [94]:
s=np.random.randint(1,19,12).reshape(3,4)
s

array([[ 1,  1, 11, 12],
       [12, 14, 18, 16],
       [10, 12, 11,  9]])

In [96]:
p=np.random.random((6)).reshape(2,3)
p

array([[0.91687145, 0.34744327, 0.73054263],
       [0.85708162, 0.1470553 , 0.37994927]])

In [98]:
f=np.random.randn(2,3)
f

array([[ 1.26494601,  0.06072767, -0.14011415],
       [ 0.26931903,  0.77160193,  1.35613414]])

In [100]:
a=np.random.randint(1,30,(10,3))
a

array([[10,  2, 10],
       [14, 16, 11],
       [25, 27, 16],
       [ 4, 24, 17],
       [11,  6, 10],
       [ 3, 19,  6],
       [16, 11, 27],
       [ 1,  8, 12],
       [ 6, 18, 17],
       [17, 28,  5]])

In [101]:
a[1:5]

array([[14, 16, 11],
       [25, 27, 16],
       [ 4, 24, 17],
       [11,  6, 10]])

In [102]:
a[2:,:2]

array([[25, 27],
       [ 4, 24],
       [11,  6],
       [ 3, 19],
       [16, 11],
       [ 1,  8],
       [ 6, 18],
       [17, 28]])

In [103]:
a

array([[10,  2, 10],
       [14, 16, 11],
       [25, 27, 16],
       [ 4, 24, 17],
       [11,  6, 10],
       [ 3, 19,  6],
       [16, 11, 27],
       [ 1,  8, 12],
       [ 6, 18, 17],
       [17, 28,  5]])

In [104]:
a>10

array([[False, False, False],
       [ True,  True,  True],
       [ True,  True,  True],
       [False,  True,  True],
       [ True, False, False],
       [False,  True, False],
       [ True,  True,  True],
       [False, False,  True],
       [False,  True,  True],
       [ True,  True, False]])

In [106]:
a[a>10]

array([14, 16, 11, 25, 27, 16, 24, 17, 11, 19, 16, 11, 27, 12, 18, 17, 17,
       28])

In [107]:
a[a>10].sum()

326

In [109]:
a.max()

28

In [110]:
a.min()

1

In [111]:
a=np.arange(9).reshape(3,3)
a

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [112]:
b=np.arange(10,19).reshape(3,3)
b

array([[10, 11, 12],
       [13, 14, 15],
       [16, 17, 18]])

In [115]:
print(a+b)
print("***************************")
print(a-b)
print("===================")
print(a*b)
print("$$$$$$$$$$$$$$$$$$$")
print(a%b)
print(np.max(a))
print(np.min(b))

[[10 12 14]
 [16 18 20]
 [22 24 26]]
***************************
[[-10 -10 -10]
 [-10 -10 -10]
 [-10 -10 -10]]
[[  0  11  24]
 [ 39  56  75]
 [ 96 119 144]]
$$$$$$$$$$$$$$$$$$$
[[0 1 2]
 [3 4 5]
 [6 7 8]]
8
10


In [116]:
# 0-15 ---->(3,15)
a=np.arange(15).reshape(3,5)
a

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [117]:
print(np.mean(a))

7.0


In [118]:
print(np.median(a))

7.0


In [119]:
b.dot(a)

array([[175, 208, 241, 274, 307],
       [220, 262, 304, 346, 388],
       [265, 316, 367, 418, 469]])

In [120]:
a

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [121]:
a+3

array([[ 3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12],
       [13, 14, 15, 16, 17]])

In [122]:
a+10

array([[10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [127]:
np.log2(2)

1.0

In [128]:
np.log([1,2,3])

array([0.        , 0.69314718, 1.09861229])

In [130]:
np.exp(1)

2.718281828459045

In [131]:
np.sin(0)

0.0

In [135]:
np.cos(0)

1.0

In [134]:
np.tan(30)

-6.405331196646276

In [136]:
import numpy
dir(numpy)

['ALLOW_THREADS',
 'AxisError',
 'BUFSIZE',
 'Bytes0',
 'CLIP',
 'ComplexWarning',
 'DataSource',
 'Datetime64',
 'ERR_CALL',
 'ERR_DEFAULT',
 'ERR_IGNORE',
 'ERR_LOG',
 'ERR_PRINT',
 'ERR_RAISE',
 'ERR_WARN',
 'FLOATING_POINT_SUPPORT',
 'FPE_DIVIDEBYZERO',
 'FPE_INVALID',
 'FPE_OVERFLOW',
 'FPE_UNDERFLOW',
 'False_',
 'Inf',
 'Infinity',
 'MAXDIMS',
 'MAY_SHARE_BOUNDS',
 'MAY_SHARE_EXACT',
 'MachAr',
 'ModuleDeprecationWarning',
 'NAN',
 'NINF',
 'NZERO',
 'NaN',
 'PINF',
 'PZERO',
 'RAISE',
 'RankWarning',
 'SHIFT_DIVIDEBYZERO',
 'SHIFT_INVALID',
 'SHIFT_OVERFLOW',
 'SHIFT_UNDERFLOW',
 'ScalarType',
 'Str0',
 'Tester',
 'TooHardError',
 'True_',
 'UFUNC_BUFSIZE_DEFAULT',
 'UFUNC_PYVALS_NAME',
 'Uint64',
 'VisibleDeprecationWarning',
 'WRAP',
 '_NoValue',
 '_UFUNC_API',
 '__NUMPY_SETUP__',
 '__all__',
 '__builtins__',
 '__cached__',
 '__config__',
 '__deprecated_attrs__',
 '__dir__',
 '__doc__',
 '__expired_functions__',
 '__file__',
 '__getattr__',
 '__git_revision__',
 '__loader__',

### Pandas
- Pandas is the datascience package
- It is used for
    - Data manuplations (mofifications and updations)
    - Data Analysis
    - Data Cleaning to remove the unneccessary data  from data sets
- Contains mainly two  data structres in pandas
    - Series- Sequence of a data
    - Data Frames- data with row and column